spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dm
    username: dm
    password: "pass"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    enabled: false
